version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/dist:/app/dist

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
